sudo: true
dist: trusty
language: cpp

matrix:
  include:

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-7
            - clang-5.0
      env: 
        - COMPILER_NAME=gcc 
        - BUILD_MODE=debug 
        - TARGETS="unit perf"
        - EVAL="sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-7 /usr/bin/g++"
      
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env: 
        - COMPILER_NAME=clang 
        - BUILD_MODE=debug 
        - TARGETS="unit fuzz perf"      
        - EVAL="sudo ln -s /usr/bin/clang++-5.0 /usr/bin/clang++"
        
before_install:
    - eval "${EVAL}"
  
before_script:   
    - cd src
    - git clone https://github.com/philsquared/Catch.git
    - cp Catch/include/catch.hpp catch.hpp
    
script:
    - which g++
    - which clang++
    - which clang++-5.0
    - g++ -v
    - clang++ -v
    - make mode=$BUILD_MODE compiler=$COMPILER_NAME $TARGETS
