sudo: false
dist: trusty
language: cpp

matrix:
  include:

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: COMPILER_NAME=gcc BUILD_MODE=debug TARGETS="unit perf"
      
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env: COMPILER_NAME=clang BUILD_MODE=debug TARGETS="unit fuzz perf"      
        
before_script:   
    - cd src
    - git clone https://github.com/philsquared/Catch.git
    - cp Catch/include/catch.hpp catch.hpp
    
script:
    - alias g++='g++-6'  
    - alias clang++='clang++-5.0'
    - make mode=$BUILD_MODE compiler=COMPILER_NAME $TARGETS
