sudo: false
dist: trusty
language: cpp

matrix:
  include:

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: CXX=g++-6 BUILD_MODE=debug TARGETS="unit perf" EXE=
      
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env: CXX=clang-5.0 BUILD_MODE=debug TARGETS="unit fuzz perf"      
        
before_script:   
    - cd src
    - git clone https://github.com/philsquared/Catch.git
    - cp Catch/include/catch.hpp catch.hpp
    
script:
    - make mode=$BUILD_MODE compiler=$CXX $TARGETS
    - ./
