sudo: true
dist: trusty
language: cpp

matrix:
  include:

    #linux gcc7 debug build
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-7

      env: 
        - COMPILER_NAME=gcc 
        - BUILD_MODE=debug 
        - TARGETS="unit perf"
        - EVAL="sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-7 /usr/bin/g++"
 
    #linux gcc7 debug undefined sanitizer build
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-7

      env: 
        - COMPILER_NAME=gcc 
        - BUILD_MODE=debug 
        - TARGETS="unit perf"
        - EVAL="sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-7 /usr/bin/g++"
        - SANITIZER=ubsan
        
    #linux gcc7 debug address sanitizer build
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-7

      env: 
        - COMPILER_NAME=gcc 
        - BUILD_MODE=debug 
        - TARGETS="unit perf"
        - EVAL="sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-7 /usr/bin/g++"
        - SANITIZER=asan
        
    #linux gcc7 release build
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-7

      env: 
        - COMPILER_NAME=gcc 
        - BUILD_MODE=release 
        - TARGETS="unit perf"
        - EVAL="sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-7 /usr/bin/g++"
    
  
 
#at the moment, it is complicated to get clang-5.0 with libc++ in travis
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - g++-7

      env: 
        - COMPILER_NAME=clang 
        - BUILD_MODE=debug 
        - TARGETS="unit perf"      
#       - TARGETS="unit fuzz perf" #using libstdc++ make it impossible to build the fuzz        
        - EVAL="sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-7 /usr/bin/g++ && sudo mv /usr/local/clang-3.5.0/bin/clang++ /usr/local/clang-3.5.0/bin/clang++Old && sudo ln -s /usr/bin/clang++-5.0 /usr/bin/clang++"
        
before_install:
    - eval "${EVAL}"
  
before_script:   
    - cd src
    - git clone https://github.com/philsquared/Catch.git
    - cp Catch/single_include/catch.hpp catch.hpp
    
script:
    - make mode=$BUILD_MODE compiler=$COMPILER_NAME $TARGETS travis=1 sanitize=$SANITIZER
    - ./radixSort
    
#TODOs:
#   split perf and unit builds and runs to reduce time?
#   test osx
#   add release build for clang
#   build in 32 bits (it is broken in local at the moment: fix it first)   
#
#   sanitizers: 
#
#make compiler=gcc sanitize=scan-build
#make compiler=gcc sanitize=ubsan
#make compiler=gcc sanitize=asan
#make compiler=gcc sanitize=tsan
#make compiler=gcc sanitize=sast

#make compiler=clang sanitize=scan-build
#make compiler=clang sanitize=ubsan
#make compiler=clang sanitize=asan
#make compiler=clang sanitize=tsan
#make compiler=clang sanitize=sast